version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for Helm
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "daily"
