project_name: caddy-ingress
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/caddy
    binary: ingress-controller
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: s390x
      - goos: freebsd
        goarch: riscv64
      - goos: freebsd
        goarch: arm
        goarm: "5"
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers_v2:
  - id: standard-registries
    images:
      - "{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
      - "{{ .Env.ACR_LOGIN_SERVER }}/{{ .ProjectName }}"
      - "{{ .Env.GAR_LOCATION }}-docker.pkg.dev/{{ .Env.GCP_PROJECT_ID }}/{{ .Env.GAR_REPOSITORY }}/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ else }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
      - linux/arm
      - linux/ppc64le
      - linux/riscv64
    labels:
      "org.opencontainers.image.description": "Caddy Ingress Controller for Kubernetes - with Cloudflare support!"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

  - id: aws-marketplace
    images:
      - "{{ .Env.ECR_REGISTRY }}/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
      - linux/arm
      - linux/ppc64le
      - linux/riscv64
    labels:
      "org.opencontainers.image.description": "Caddy Ingress Controller for Kubernetes - with Cloudflare support!"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
