project_name: caddy-ingress
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/caddy
    binary: ingress-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers_v2:
  - images:
      - "butlergroup/{{ .ProjectName }}:test-image"
      - "butlergroup/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "butlergroup/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
      - "butlergroup/{{ .ProjectName }}:{{ .Tag }}-s390x"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Caddy ingress controller for Kubernetes - with Cloudflare support!"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
    artifacts: all

release:
  disable: true

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
