FROM golang:1.26@sha256:633d23bf362cb40dd72b4f277288a8929697d77537f9c801b81aeced19b5bdf3 as build

ENV CGO_ENABLED=0

WORKDIR /go/ingress-controller

COPY go.mod go.sum /go/ingress-controller/
RUN go mod download

COPY . .
RUN go build -o ./bin/ingress-controller ./cmd/caddy

FROM alpine:latest@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

# added zlib to address CVE-2026-22184
# added openssl to address CVE-2026-2673
# added musl to address CVE-2026-40200
RUN apk update && \
    apk add --no-cache --upgrade \
        zlib \
        openssl \
        musl 

EXPOSE 80 443

COPY --from=build /go/ingress-controller/bin/ingress-controller /ingress-controller

ENTRYPOINT ["/ingress-controller"]