FROM golang:1.27@sha256:7543a96ce82c8e9003cae079ee3e0bc5b7799df8eed2a041e403af0d31fa4e67 as build

ENV CGO_ENABLED=0

WORKDIR /go/ingress-controller

COPY go.mod go.sum /go/ingress-controller/
RUN go mod download

COPY . .
RUN go build -o ./bin/ingress-controller ./cmd/caddy

FROM alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# added zlib to address CVE-2026-22184
# added openssl to address CVE-2026-2673
# added musl to address CVE-2026-40200
RUN apk update && \
    apk add --no-cache --upgrade \
        zlib \
        openssl \
        musl 

EXPOSE 80 443

COPY --from=build /go/ingress-controller/bin/ingress-controller /ingress-controller

ENTRYPOINT ["/ingress-controller"]