FROM golang:1.27@sha256:3680233e3204827fbdc66088528ae6d4b3d034f51d03a99d454f6de034888244 as build

ENV CGO_ENABLED=0

WORKDIR /go/ingress-controller

COPY go.mod go.sum /go/ingress-controller/
RUN go mod download

COPY . .
RUN go build -o ./bin/ingress-controller ./cmd/caddy

FROM alpine:latest@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

# added zlib to address CVE-2026-22184
# added openssl to address CVE-2026-2673
# added musl to address CVE-2026-40200
RUN apk update && \
    apk add --no-cache --upgrade \
        zlib \
        openssl \
        musl 

EXPOSE 80 443

COPY --from=build /go/ingress-controller/bin/ingress-controller /ingress-controller

ENTRYPOINT ["/ingress-controller"]