x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: Initial release.
    releaseTypes:
      - Feature
      - BugFix
      - Security
    recommended: true

  images:
    caddy-ingress:
      properties:
        gcpMarketplace.image.registry:
          type: REGISTRY
        gcpMarketplace.image.repository:
          type: REPO_WITHOUT_REGISTRY
        gcpMarketplace.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  replicaCount:
    type: integer
    default: 1

  operatorServiceAccount:
    type: string
    title: Operator Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                  - "networking.k8s.io"
                  - "coordination.k8s.io"
                resources:
                  - ingresses
                  - ingresses/status
                  - secrets
                  - leases
                verbs: ["get", "list", "watch", "create", "update", "delete"]
              - apiGroups:
                  - ""
                resources:
                  - services
                  - pods
                  - nodes
                  - routes
                  - extensions
                  - configmaps
                verbs: ["list", "get", "watch"]

  ingress:
    type: boolean
    default: true
    x-google-marketplace:
      type: INGRESS_AVAILABLE

  deployer:
    type: string
    default: "$REGISTRY/deployer:$TAG"
    x-google-marketplace:
      type: DEPLOYER_IMAGE

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - reportingSecret
